version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:?MONGO_INITDB_ROOT_USERNAME is not set}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:?MONGO_INITDB_ROOT_PASSWORD is not set}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      container_name: backend
      environment:
        - MONGODB_URI=${MONGODB_URI:?MONGODB_URI is not set}
      ports:
        - "8080:8080"
      depends_on:
        - mongodb

volumes:
  mongodb_data:

